coverage:
  status:
    patch:
      default:
        target: 50%
        threshold: 5%
        if_ci_failed: error
    project:
      default:
        target: 50%
        threshold: 5%
        if_ci_failed: error
