name: "📦 Release Drafter"

on:
  push:
    branches:
      - ci/release-drafter-test

permissions:
  contents: write
  pull-requests: write

jobs:
  update-release-draft:
    name: update-relase-draft
    runs-on: ubuntu-latest
    
    steps:
      - name: Cria novo draft de release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: configs/release-drafter.yml

      - name: Verifica resovled version
        run: |
          echo $RESOLVED_VERSION
